package com.dematicket.form;

import com.dematicket.bean.TipoCambioVO;
import com.dematicket.data.TipoCambioDAO;
import com.dematicket.data.UsuarioData;
import static com.dematicket.form.FormTicket.lblExchangeRate;
import com.dematicket.util.Util;
import com.toedter.calendar.JCalendar;
import java.awt.Toolkit;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author lmonge
 */
public class FormExchangeRate extends javax.swing.JFrame {
    String cabecera = "";
    ArrayList<String> detalle = new ArrayList();
    private JCalendar calendar;
    /**
     * Creates new form FormTicket
     */
    public FormExchangeRate() {
        initComponents();
        loadComponentes();    
        calendar = new JCalendar();
        calendar.setBounds(15, 20, 280, 120);
        //jPanel1.add(calendar);
        calendar.setEnabled(true);
        calendar.getDayChooser().addPropertyChangeListener(
                new java.beans.PropertyChangeListener() {
 
                    @Override
                    public void propertyChange(java.beans.PropertyChangeEvent evt) {
                        if (evt.getPropertyName().compareTo("day") == 0) {
                            SimpleDateFormat formatoDeFecha = new SimpleDateFormat("yyyy-MM-dd");
                            //txtFechaSeleccionada.setText(formatoDeFecha.format(calendar.getDate()));
                            //JOptionPane.showMessageDialog(null, formatoDeFecha.format(calendar.getDate()), "DmPos", JOptionPane.WARNING_MESSAGE);         
                            TipoCambioVO tipoCambioxDia = TipoCambioDAO.consultarTipoCambioxDia(formatoDeFecha.format(calendar.getDate()));
                            if(tipoCambioxDia == null){
                                JOptionPane.showMessageDialog(null, 
                                        "NO EXISTE TIPO DE CAMBIO PARA EL DIA SELECCIONADO", "DmPos", JOptionPane.INFORMATION_MESSAGE);
                                exchangeRateBuy.setText("");
                                exchangeRateSell.setText("");
                                return;
                            }else{
                                exchangeRateBuy.setText(tipoCambioxDia.getTcompra());
                                exchangeRateSell.setText(tipoCambioxDia.getTventa());
                            }    
                        }
                    }
                });
        
        
        jPanel3.add(calendar);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exchangeRateBuy = new javax.swing.JTextField();
        btnOKPassChange = new javax.swing.JButton();
        exchangeRateSell = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Compra :");

        jLabel2.setText("Venta :");

        exchangeRateBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchangeRateBuyActionPerformed(evt);
            }
        });
        exchangeRateBuy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                exchangeRateBuyKeyTyped(evt);
            }
        });

        btnOKPassChange.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnOKPassChange.setText("Grabar");
        btnOKPassChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKPassChangeActionPerformed(evt);
            }
        });

        exchangeRateSell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                exchangeRateSellKeyTyped(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Actualizado a    "));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOKPassChange)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exchangeRateSell, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exchangeRateBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(exchangeRateBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(exchangeRateSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOKPassChange)
                .addContainerGap())
        );

        jPanel3.getAccessibleContext().setAccessibleName("Fecha de Ingreso");
        jPanel3.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exchangeRateBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchangeRateBuyActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_exchangeRateBuyActionPerformed

    private void btnOKPassChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKPassChangeActionPerformed
        try {
            // TODO add your handling code here:
            SimpleDateFormat formatoDeFecha = new SimpleDateFormat("yyyy-MM-dd");
            Date fechaCalendario = formatoDeFecha.parse(formatoDeFecha.format(calendar.getDate()));            
            java.util.Date fechaActual = new Date();
            Date actual= formatoDeFecha.parse(formatoDeFecha.format(fechaActual));
            //JOptionPane.showMessageDialog(null,fechaCalendario.compareTo(actual) , "DmPos", JOptionPane.WARNING_MESSAGE);
            if(fechaCalendario.compareTo(actual)!= 0 ){
                JOptionPane.showMessageDialog(null, "NO SE PUEDE GRABAR UN TIPO DE CAMBIO PARA UNA FECHA DISTINTA A LA DE HOY", "DmPos", JOptionPane.WARNING_MESSAGE);
                exchangeRateBuy.setText("");
                exchangeRateSell.setText("");
                return;
            }            
            TipoCambioDAO tipoCambioDAO = new TipoCambioDAO();
            boolean exito= true;
            exito= tipoCambioDAO.insertarActualizarTipoCambio(exchangeRateBuy.getText(), exchangeRateSell.getText());
            if(exito){
                JOptionPane.showMessageDialog(null, "TIPO DE CAMBIO GRABADO CORRECTAMENTE", "DmPos", JOptionPane.WARNING_MESSAGE);
                TipoCambioVO tipoCambioVO = TipoCambioDAO.consultarTipoCambio();
                lblExchangeRate.setText(tipoCambioVO.getTventa());
                this.setVisible(false);
            }else{ 
                JOptionPane.showMessageDialog(null, "NO SE PUDO GRABAR TIPO DE CAMBIO", "DmPos", JOptionPane.WARNING_MESSAGE);
            }
        } catch (ParseException ex) {
            Logger.getLogger(FormExchangeRate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOKPassChangeActionPerformed

    private void exchangeRateBuyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exchangeRateBuyKeyTyped
        // TODO add your handling code here:
        char kc = (char) evt.getKeyChar();
        if(Util.validaSoloNumero(kc)== false){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_exchangeRateBuyKeyTyped

    private void exchangeRateSellKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exchangeRateSellKeyTyped
        // TODO add your handling code here:
        char kc = (char) evt.getKeyChar();
        if(Util.validaSoloNumero(kc)== false){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_exchangeRateSellKeyTyped

    private void loadComponentes(){
        String path = new File ("").getAbsolutePath();
        path = path+"\\img\\";
        this.setTitle("DmPos - Actualizar Tipo Cambio");
        //this.setIconImage(new ImageIcon(path+"logowindow.png").getImage());         
        if(UsuarioData.getUsuario().getEmpresa().equals("1")){
           this.setIconImage(new ImageIcon(path+"logowindow.png").getImage());
        }
        if(UsuarioData.getUsuario().getEmpresa().equals("2")){
           this.setIconImage(new ImageIcon(path+"logowindowCrisol.png").getImage());           
        }
        TipoCambioVO tipoCambioVO = TipoCambioDAO.consultarTipoCambio();
        if(tipoCambioVO != null){
            exchangeRateBuy.setText(tipoCambioVO.getTcompra());
            exchangeRateSell.setText(tipoCambioVO.getTventa());
        }
        
    }
    public void Limpiar(){
       
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOKPassChange;
    private javax.swing.JTextField exchangeRateBuy;
    private javax.swing.JTextField exchangeRateSell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
